job_titles:
  - Data Scientist
  - ML Engineer
  - DevOps
  - MLOps
  - Data engineer
  - Cloud Engineer
  - Productin engineer
ideal_job_description: >
  Technical role in the field of data, machine learning, building data pipelines or cloud engineering.
  The focus is on junior full-time positions or internships with limited technical experience required.

technical_skills:
  - Python
  - SQL
  - AWS
  - Scikit-learn
  - Git
education_level: Master's degree in Data Science
experience: Beginner (less than 3 years)
