name: Daily Job Recommendation

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  JOOBLE_API_KEY: ${{ secrets.JOOBLE_API_KEY }}
  ADZUNA_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ADZUNA_API_ID: ${{ secrets.JOOBLE_API_KEY }}
  SENDGRID_API_KEY: ${{ secrets.OPENAI_API_KEY }}


on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-recommender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python generate_top_jobs.py
          streamit run app.py
